version: '3.3'

services:
  app:
    stdin_open: true
    tty: true
    build: .
    ports:
      - "${LABEL_STUDIO_PORT_EXT:-8080}:8080"
    depends_on:
      - db
    environment:
      DJANGO_DB: default
      POSTGRE_NAME: postgres
      POSTGRE_USER: postgres
      POSTGRE_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRE_PORT: 5432
      POSTGRE_HOST: db
      LABEL_STUDIO_HOST: "${LABEL_STUDIO_HOST:-}"
      LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK: "true"
      LABEL_STUDIO_USERNAME: "${LABEL_STUDIO_USERNAME}"
      LABEL_STUDIO_PASSWORD: "${LABEL_STUDIO_PASSWORD}"
#     volumes:
#       - ./mydata:/label-studio/data:rw
    command: [ "./deploy/wait-for-postgres.sh", "bash", "/label-studio/deploy/start_label_studio.sh" ]

  db:
    image: postgres:11.5
    hostname: db
#     restart: always
    ports:
      - "${POSTGRES_PORT_EXT:-8080}:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  static: {}
  pgdata: {}