# Generated by Django 3.1.12 on 2021-08-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectgroup',
            name='children',
        ),
        migrations.RemoveField(
            model_name='projectgroup',
            name='projects',
        ),
    ]
