# Generated by Django 3.1.12 on 2021-08-25 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_projectsample'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectsample'),
        ),
    ]
