# Generated by Django 3.1.12 on 2021-08-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
