# Generated by Django 3.1.12 on 2021-08-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_is_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_template',
            field=models.BooleanField(default=True),
        ),
    ]
