# Generated by Django 3.1.12 on 2021-08-29 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0021_projectgroup_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_groups',
            field=models.ManyToManyField(to='projects.UserGroup'),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
