# Generated by Django 3.1.12 on 2021-08-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20210829_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectUser',
        ),
    ]
