# Generated by Django 3.1.12 on 2021-09-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_delete_projectuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sample',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
