# Generated by Django 3.1.12 on 2021-09-22 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20210922_2133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectSample',
        ),
    ]
