# Generated by Django 3.1.12 on 2021-09-22 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_delete_projectsample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.project'),
        ),
    ]
