# Generated by Django 3.1.12 on 2022-02-21 02:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0028_project_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='user_groups',
            field=models.ManyToManyField(to='projects.UserGroup'),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
